#!/bin/bash
#
# import-mc - Import MC runs from another directory.

if [ $# = 0 ]; then
    >&2 echo "usage: $(basename "$0") <source-mc-dir>"
    exit 1
fi
S_MCDIR=$1
D_MCDIR=$(readlink -f mc)

for PROC in $(ls ${S_MCDIR} 2>/dev/null); do
    echo "Working on ${S_MCDIR}/${PROC}..."
    pushd ${S_MCDIR}/${PROC} >/dev/null
    for RUNDIR in $(./list-run 2>/dev/null | awk '{print $1}'); do
        # Create symbolic links.
        LOGDIR=log${RUNDIR:3}
        RUNDIR=${RUNDIR}/Events/run_01
        rm -rf ${D_MCDIR}/${PROC}/${RUNDIR} ${D_MCDIR}/${PROC}/${LOGDIR}
        mkdir -p ${D_MCDIR}/${PROC}/${RUNDIR} ${D_MCDIR}/${PROC}/${LOGDIR}
        ln -s $(readlink -f ${RUNDIR}/*) ${D_MCDIR}/${PROC}/${RUNDIR}
        ln -s $(readlink -f ${LOGDIR}/*) ${D_MCDIR}/${PROC}/${LOGDIR}

        # Supplement ExRootAnalysis result on demand.
        if [ ! -r ${RUNDIR}/unweighted_events.root ]; then
            echo "Converting: ${RUNDIR}/unweighted_events.lhe.gz -> unweighted_events.root"
            gzip -cd ${RUNDIR}/unweighted_events.lhe.gz > ${D_MCDIR}/${PROC}/${RUNDIR}/unweighted_events.lhe
            ${D_MCDIR}/../resource/MG5_aMC/ExRootAnalysis/ExRootLHEFConverter \
                ${D_MCDIR}/${PROC}/${RUNDIR}/unweighted_events.lhe \
                ${D_MCDIR}/${PROC}/${RUNDIR}/unweighted_events.root
            rm ${D_MCDIR}/${PROC}/${RUNDIR}/unweighted_events.lhe
        fi

        # Supplement Delphes result on demand.
        if [ ! -r ${RUNDIR}/tag_1_delphes_events.root ]; then
            echo "Converting: ${RUNDIR}/tag_1_pythia8_events.hepmc.gz -> tag_1_delphes_events.root"
            rm ${D_MCDIR}/${PROC}/${RUNDIR}/tag_1_delphes.log
            gzip -cd ${RUNDIR}/tag_1_pythia8_events.hepmc.gz | \
                ${D_MCDIR}/../resource/MG5_aMC/Delphes/DelphesHepMC2 \
                ${RUNDIR}/../../Cards/delphes_card.dat \
                ${D_MCDIR}/${PROC}/${RUNDIR}/tag_1_delphes_events.root \
                - &> ${D_MCDIR}/${PROC}/${RUNDIR}/tag_1_delphes.log
        fi &
    done
    popd >/dev/null
done
wait
