#!/bin/bash
#
# g++ - inject ${INJECT_CXXFLAGS} and ${INJECT_LDFLAGS}
#
# This script wraps the original g++ program, which is found
# based on environment ${PATH}.

exec /usr/bin/g++ ${INJECT_CXXFLAGS} "$@" ${INJECT_LDFLAGS}
