#!/bin/bash
#
# make - force concurrent build of projects
#
# This script wraps the original make program, which is found
# based on environment ${PATH}.

exec /usr/bin/make -j$(cat /proc/cpuinfo | grep MHz | wc -l) CXX=g++ LD=g++ "$@"
