#!/bin/bash
#
# mg5_aMC - run mg5_aMC and clean up py.py
#
# This script wraps the original mg5_aMC, whose path is hard-
# coded for this project.
#
# Update on Aug 17, 2023: Source thisroot.sh (maybe again) to
# enhance robustness.

source "$(dirname "$0")"/root/bin/thisroot.sh
trap '>&2 echo "$0": removing py.py...; rm -f py.py' EXIT
trap 'exit 1' SIGINT SIGQUIT SIGTERM
"$(dirname "$0")"/MG5_aMC/bin/mg5_aMC "$@"
