#!/bin/bash
#
# loop-all - Run loop-run on all nodes.

# NOTE: DONOT run on farm for other people's convenience.
for NODE in node01 node03 node05 node06 atlas; do
    echo ${NODE}
    ssh ${NODE} "cd ${PWD} && (./loop-run </dev/null &>/dev/null &)"
done
