#!/bin/bash
#
# run-proc - Run generated process.

# Avoid re-entrant.
if ./list-run 127>&1 1>/dev/null 2>&127 | grep ${HOSTNAME} | grep -q busy; then
    >&2 echo 'Exiting on busyness...'
    exit 1
fi

# Find and lock ${RUNNAME}.
mkdir -p log run || exit
while true; do
    RUNNAME=${HOSTNAME}-$(date +%s.%N)
    if mkdir log/${RUNNAME} 2>/dev/null; then
        cp -r proc run/${RUNNAME} || exit
        break
    fi
    sleep $(printf '0.%06ds' ${RANDOM})  # mitigate contention
done

# ${RUNNAME} -> ${RANDSEED}
seed() {
    local HASH="$(md5sum <<< "$*")"
    echo $[0x${HASH:0:12} % 900000000]  # max for MG5_aMC@NLO: 30081*30081 with bias >= 1
                                        # max for bash: 2**63-1 (int64_t)
}

# Hide incompatible lhapdf installation.
export LD_LIBRARY_PATH=$(echo $LD_LIBRARY_PATH | sed 's@\(^\|:\)[^:]*lhapdf[^:]*@@g')

exec ../../resource/mg5_aMC 0<<< "!date
launch run/${RUNNAME} -m
$(cat /proc/cpuinfo | grep MHz | wc -l)
shower=Pythia8
detector=Delphes
analysis=ExRoot
done
set nevents=100000
set iseed=$(seed ${RUNNAME})
set pdlabel=lhapdf
set lhaid=331100
done
!date" 1> log/${RUNNAME}/1.log 2> log/${RUNNAME}/2.log
