#!/bin/bash
#
# loop-all - Run loop-run on all nodes.

# NOTE: DONOT run on farm for other people's convenience.
for NODE in "$@"; do
    echo ${NODE}
    ssh ${NODE} "cd ${PWD} && (./loop-run </dev/null &>/dev/null &)"
done
