#!/bin/bash
#
# select-run - Select split Delphes events.

for ROOTFILE in $(ls split/*/*_delphes_events_*.root); do
    DUMPFILE=$(echo ${ROOTFILE} | sed 's@_delphes_events_@_selected_events_@')
    LOGFILE=$(echo ${ROOTFILE} | sed 's@_delphes_events_@_selected_events_@' | sed 's@\.root$@\.log@')
    if [ -e ${DUMPFILE} ]; then continue; fi
    echo ${ROOTFILE}
    ../../bin/delphes-select ${ROOTFILE} ${DUMPFILE} &> ${LOGFILE} &
done
