#!/bin/bash
#
# split-run - Split Delphes events into ${NEVT} events per ROOT file.

NEVT=$1
shift
if [ $# != 0 ]; then
    SRCDIRS="$*"
else
    SRCDIRS="$(./list-run 2>/dev/null | awk '{print $1}')"
fi

mkdir -p split
SPLIT=$(readlink -f ../../bin/delphes-split)
for SRCDIR in ${SRCDIRS}; do
    DSTDIR=split${SRCDIR:3}
    SRCDIR=$(readlink -f ${SRCDIR})
    if [ -e ${DSTDIR} ]; then continue; fi
    mkdir -p ${DSTDIR}
    pushd ${DSTDIR}
    ${SPLIT} ${SRCDIR}/Events/run_01/tag_1_delphes_events.root ${NEVT} &> split.log &
    popd
done
