#!/bin/bash
#
# async-run-proc - Run generated process asynchronously.

mkdir -p logs

PROGNAME=$(basename $0)
PROGNAME=${PROGNAME:6}
LOGNAME=logs/${PROGNAME}-${HOSTNAME}-$(date +%s)
(./${PROGNAME} 0< /dev/null 1> ${LOGNAME}-1.log 2> ${LOGNAME}-2.log &)
