#!/bin/bash
#
# run-proc - Run generated process.

# Find and lock ${RUNNAME}.
mkdir -p log run || exit
while true; do
    RUNNAME=${HOSTNAME}-$(date +%s.%N)
    if mkdir log/${RUNNAME} 2>/dev/null; then
        cp -r proc run/${RUNNAME} || exit
        break
    fi
    sleep $(printf '0.%06ds' ${RANDOM})  # mitigate contention
done

(../resource/mg5_aMC 0<<< "!date
launch run/${RUNNAME} -m
$(cat /proc/cpuinfo | grep MHz | wc -l)
shower=Pythia8
detector=Delphes
analysis=ExRoot
done
set nevents=100000
done
!date" 1> log/${RUNNAME}/1.log 2> log/${RUNNAME}/2.log &)
