#!/bin/bash
#
# run-proc - Run generated process.

# Avoid re-entrant.
if ./list-run 127>&1 1>/dev/null 2>&127 | grep ${HOSTNAME} | grep -q busy; then
    >&2 echo 'Exiting on busyness...'
    exit 1
fi

# Find and lock ${RUNNAME}.
mkdir -p log run || exit
while true; do
    RUNNAME=${HOSTNAME}-$(date +%s.%N)
    if mkdir log/${RUNNAME} 2>/dev/null; then
        cp -r proc run/${RUNNAME} || exit
        break
    fi
    sleep $(printf '0.%06ds' ${RANDOM})  # mitigate contention
done

exec ../resource/mg5_aMC 0<<< "!date
launch run/${RUNNAME} -m
$(cat /proc/cpuinfo | grep MHz | wc -l)
shower=Pythia8
detector=Delphes
analysis=ExRoot
done
set nevents=100000
done
!date" 1> log/${RUNNAME}/1.log 2> log/${RUNNAME}/2.log
