#!/usr/bin/env python3
#
# list-run - List MG5_aMC@NLO run results.

import os
import re
import sys

re_log1 = re.compile(
    # 1                    2             3       4                          5            6
    # RPT                  CS            CS-ERR  CS-UNIT                    NEVT    FIN  QUIT
    r'(Cross-section\s*:\s*(\S+)\s*\+-\s*(\S+)\s*(\S+)\s*Nb of events\s*:\s*(\S+)).*\1.*^(quit)?$',
    re.M | re.S
)

node_stat = { }
nevt_total = 0

for name in sorted(os.listdir('log')):
    with open(os.path.join('log', name, '1.log')) as log1:
        log1 = log1.read()
        m_log1 = re_log1.search(log1)
        node = name.split('-')[0]
        node_stat[node] = node_stat.get(node, False) | ((not m_log1) or (not m_log1.group(6)))
        if m_log1 is None:
            print(os.path.join('log', name), 'running', *log1.split('\n')[-2:-1], sep='\t', file=sys.stderr)
        else:
            print(os.path.join('run', name), *m_log1.groups()[1:-1], sep='\t')
            nevt_total += int(m_log1.group(5))

for node, stat in node_stat.items(): print('%s:\t%s' % (node, 'busy' if stat else 'idle'), sep='\t', file=sys.stderr)
print('total:\t%d' % (nevt_total), sep='\t', file=sys.stderr)
