#!/bin/bash
#
# loop-run - Run run-proc until enough ${NEVT}.

TARGET=100

# Loop until enough events.
while true; do
    NEVT=$(./list-run 127>&1 1>/dev/null 2>&127 | grep total: | grep -o '[0-9]\+')
    if [ ${NEVT} -ge ${TARGET} ]; then
        >&2 echo 'Exiting on success...'
        exit 0
    fi
    if ! ./run-proc; then
        >&2 echo 'Exiting on failure...'
        exit 1
    fi
done
